apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sparkel-gosys
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  kafka:
    pool: nav-dev
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/dev/srvsparkelgosys
  env:
  - name: KAFKA_CONSUMER_GROUP_ID
    value: tbd-sparkel-gosys-v1
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
  - name: STS_BASE_URL
    value: http://security-token-service.default.svc.nais.local
  - name: OPPGAVE_URL
    value: http://oppgave.default.svc.nais.local

